### PR TITLE
Bring in initial TCK tests

### PR DESCRIPTION
**Pull request by ayoho**
Related to #5
Initial delivery of TCK tests. This PR adds a single optional test class from the MP JWT Auth TCK: EjbTest.

### CODE REVIEW

**Comment by ayoho** [comment]
@sberyozkin How does this look to start us off?

**Comment by sberyozkin** [comment]
Apologies @ayoho for missing out on your PR, thanks a million for the effort, let me have a look asap, I'll also request others to double check, cheers

**Comment by sberyozkin** [comment]
Hey @ayoho I pushed a minor update, specifically, the build was failing because it was trying to execute the TCK test. I also prepared the tests to run for the utility tests, since we'll use those utilities to create TCKs, but those tests can be moved next, would you like to follow up with a minor PR ?

**Review by sberyozkin — APPROVED** [review]

**Comment by ayoho** [comment]
@sberyozkin Thanks! Forgot I was running with `-DskipTests` locally to get everything going. Yes, I'll follow up with an additional PR for the utility tests.

**Comment by sberyozkin** [comment]
@ayoho Np at all, thanks for starting the process, and great you will follow up with another PR to complete the TCK move, cheers

**Pull request merged**
